Rel_Temp/Rel_Temp/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('relative/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

Rel_Temp/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('other/', views.other, name='other'),
    path('rel_temp/', views.rel_temp, name='rel_temp'),
]

Rel_Temp/basic_app/models.py
from django.db import models

# Create your models here.

Rel_Temp/basic_app/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'basic_app/index.html')


def other(request):
    return render(request, 'basic_app/other.html')


def rel_temp(request):
    return render(request, 'basic_app/rel_temp.html')

Rel_Temp/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <title>Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class=""container">
            <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
        </div>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">HOME <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:other' %}">OTHER</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:rel_temp' %}">RELATIVE</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
                </li>
            </ul>
        </div>
    </nav>
        <div class="container">
            {% block content %}
              <h1>This is the body of BASE PAGE where others are inheriting from</h1>
            {% endblock %}
        </div>
</body>
</html>

Rel_Temp/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block content %}
    <h1>This is the HOMEPAGE!</h1>
{% endblock %}

Rel_Temp/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block content %}
    <h1>This is the OTHER PAGE!</h1>
    <a href="{% url 'index' %}">Go back to HomePage</a>
{% endblock %}

Rel_Temp/templates/basic_app/rel_temp.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block content %}
    <h1>This is the RELATIVE TEMPLATE PAGE!</h1>
     <a href="{% url 'index' %}">Go back to HomePage</a>
{% endblock %}